In [2]:
def readFASTAs(fileName):

    with open(fileName, 'r') as file:
        v = []
        genome = ''
        for line in file:
            if line[0] != '>':
                genome += line.strip()
            else:
                v.append(genome.upper())
                genome = ''
        v.append(genome.upper())
        del v[0]
        return v

In [3]:
Sequences = readFASTAs('hotCold.txt')

In [4]:
len(Sequences)

1081

In [5]:
import itertools
import numpy as np

In [6]:
def generate(X):

    elements = 'ACGT'

    T = []
    for x in X:
        t = []
        for i in range(1, 4 + 1, 1):
            v = list(itertools.product(elements, repeat=i))
            for i in v:
                t.append(x.count(''.join(i)))
        T.append(t)

    T = np.array(T)

    return T

<br/>

* K-mer 

In [7]:
K_mer = generate(Sequences)
np.save(file = "K-mer", arr = K_mer)

<br/>

* Reverse complement composition of k-mers

In [8]:
def reverseComplement(sequence):
    c = {'A':'T', 'T':'A', 'C':'G', 'G':'C'}

    v = ''
    for bp in sequence:
        v = c[bp] + v
    return v

In [9]:
rev_k = []
for sequence in Sequences:
    rev_k.append(reverseComplement(sequence))

rev_k = generate(rev_k)
np.save(file = "rev-k-mer", arr = rev_k)

In [10]:
K_mer    = np.load('K-mer.npy')
rev_k    = np.load('rev-k-mer.npy')
print(K_mer)
print("")
print(rev_k)

[[35 39 31 ...  2  0  0]
 [38 23 44 ...  0  0  0]
 [36 32 35 ...  0  1  0]
 ...
 [37 28 32 ...  1  1  1]
 [37 28 32 ...  1  1  1]
 [29 34 27 ...  1  2  1]]

[[26 31 39 ...  0  1  1]
 [26 44 23 ...  0  1  0]
 [28 35 32 ...  0  1  0]
 ...
 [34 32 28 ...  1  1  2]
 [34 32 28 ...  1  1  2]
 [41 27 34 ...  0  1  0]]


<br/>

* n-gapped k-mer

In [11]:
def kmers(x, k):
    v = []
    for i in range(len(x) - k + 1):
        v.append(x[i:i + k])
    return v

In [22]:
import itertools
import numpy as np

def monoMonoGgap(x, g):  

    t = []
    m = list(itertools.product('ACGT', repeat=2))
    for i in range(1, g + 1, 1):
        V = kmers(x, i + 2)

        for gGap in m:

            C = 0
            for v in V:
                if v[0] == gGap[0] and v[-1] == gGap[1]:
                    C += 1

            t.append(C)

    return t

T = []
for x in Sequences:
    T.append(monoMonoGgap(x, 5))

T = np.array(T)
T

array([[11,  9,  9, ...,  8,  6,  6],
       [11,  6, 13, ...,  3,  4,  6],
       [ 7,  8, 16, ...,  7,  7,  6],
       ...,
       [11,  5,  9, ...,  8,  7,  5],
       [11,  5,  9, ...,  8,  7,  5],
       [ 7,  6,  9, ..., 10,  7, 15]])

In [23]:
print(T.shape)
np.save(file = "gapped_k_mer", arr = T)

(1081, 80)
